artifact_uri: file:C:\Users\DELL\OneDrive\Escritorio\Especializacion\Producto_datos\PRE-08-mlflow-tracking-local-carolinacgj\my_mlruns/293563735783196716/a3f13879a76c4c4282ff664d5edf047b/artifacts
end_time: 1748223856651
entry_point_name: ''
experiment_id: '293563735783196716'
lifecycle_stage: active
run_id: a3f13879a76c4c4282ff664d5edf047b
run_name: elasticnet_c90906bc
run_uuid: a3f13879a76c4c4282ff664d5edf047b
source_name: ''
source_type: 4
source_version: ''
start_time: 1748223856554
status: 3
tags: []
user_id: DELL
